apiVersion: apps/v1
kind: Deployment
metadata:
  name: safety-injuries-api
  labels:
    io.kompose.service: safety-injuries-api
  annotations:
    # ИСПРАВЛЕНО: Вместо "semver" указываем "minor" (или "patch")
    keel.sh/policy: minor
    # Включаем опрос реестра
    keel.sh/trigger: poll
    # Интервал опроса (каждые 20 минут)
    keel.sh/pollSchedule: "@every 20m"
spec:
  replicas: 1
  selector:
    matchLabels:
      io.kompose.service: safety-injuries-api
  template:
    metadata:
      labels:
        io.kompose.service: safety-injuries-api
    spec:
      imagePullSecrets:
        - name: ghcr-secret
      containers:
        - name: safety-injuries-api
          image: ghcr.io/marat1905/safetyinjuryregistry-api:1.2.0
          imagePullPolicy: Always
          ports:
            - containerPort: 8081
              protocol: TCP
            - containerPort: 8080
              protocol: TCP
          env:
            - name: ASPNETCORE_ENVIRONMENT
              value: "Production"
            - name: ASPNETCORE_HTTP_PORTS
              value: "8080"
            - name: ConnectionStrings__DefaultConnection
              value: "Host=safety-injuries-db;Port=5432;Database=safetyinjuries;Username=safetyuser;Password=12345678"
      restartPolicy: Always