apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  labels:
    io.kompose.service: safety-injuries-db-data
  name: safety-injuries-db-data
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 200Gi